Vendor/Models/Outlet.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Vendor.Models
{
    public class Outlet
    {
        public Outlet()
        {
            PointOfSales = 1;
        }
        public int Id { get; set; }
        public string Name { get; set; }
        public Store Store { get; set; }
        public int StoreId { get; set; }
        public int PointOfSales { get; set; }
    }
}

Vendor/Controllers/AccountsController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using System.Transactions;
using Vendor.Data;

namespace Vendor.Controllers
{
    public class AccountsController : BaseController
    {

        private ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public AccountsController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        public async Task<IActionResult> Index(int? id, string Range="Daily")
        {
            var outlet = _context.Outlets.Find(id);
            if (outlet == null)
            {
                return NotFound();
            }
            var loggedInUser = _userManager.GetUserId(User);
            var outletOwner = _context.Stores.Find(outlet.StoreId);
            if (!UserValid(loggedInUser, outletOwner.UserId))
            {
                return Unauthorized();
            }
           
            var transactions = await _context.Transactions.Where(t => t.OutletId == outlet.Id).ToListAsync();
            var data =  transactions.GroupBy(t => t.TransactionTime.Month).Select(t => new
            {
                Name = "Monthly Transaction",
                Date = t.Select(t => t.TransactionTime.Month).First(),
                Sum = t.Select(t => t.Amount).Sum(),
            });
            return View(); 
            //return Ok(data);
        }
    }
}

Vendor/Controllers/MenusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Vendor.Constants;
using Vendor.Data;
using Vendor.Models;
using Vendor.Models.ViewModels;

namespace Vendor.Controllers
{
    public class MenusController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MenusController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Menus
        public async Task<IActionResult> Index(int outletId)
        {
            if (outletId == null)
            {
                return Ok("Yen");
                //return NotFound();
            }
            ViewData["outletId"] = outletId;
            var menus =await _context.Menus.Where(o => o.OutletId == outletId).Include(m => m.Outlet).ToListAsync();
            var viewModel = new MenuIndexViewModel
            {
                Menus = menus,
                OutletId = outletId
            };
            return View(viewModel);
        }

        // GET: Menus/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var menu = await _context.Menus
                .Include(m => m.Outlet)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (menu == null)
            {
                return NotFound();
            }

            return View(menu);
        }

        // GET: Menus/Create
        public IActionResult Create(int? id)
        {
            var selectList = _context.Outlets.Where(o => o.Id == id);
            ViewData["OutletId"] = new SelectList(selectList, "Id", "Name");
            return View();
        }

        // POST: Menus/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Amount,OutletId")] Menu menu)
        {
            if (ModelState.IsValid)
            {
                _context.Add(menu);
                await _context.SaveChangesAsync();
                TempData[SD.Success] = "Menu Item Created Successfully";
                return RedirectToAction(nameof(Index),new {OutletId =menu.OutletId });
            }
            ViewData["LocationId"] = new SelectList(_context.Outlets, "Id", "Id", menu.OutletId);
            TempData[SD.Error] = "Unable to Create Menu Item";        
            return View(menu);
        }

        // GET: Menus/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var menu = await _context.Menus.FindAsync(id);
            if (menu == null)
            {
                return NotFound();
            }
            ViewData["LocationId"] = new SelectList(_context.Outlets, "Id", "Id", menu.OutletId);
            return View(menu);
        }

        // POST: Menus/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Amount,LocationId")] Menu menu)
        {
            if (id != menu.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(menu);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MenuExists(menu.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["LocationId"] = new SelectList(_context.Outlets, "Id", "Id", menu.OutletId);
            return View(menu);
        }

        // GET: Menus/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var menu = await _context.Menus
                .Include(m => m.OutletId)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (menu == null)
            {
                return NotFound();
            }

            return View(menu);
        }

        // POST: Menus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var menu = await _context.Menus.FindAsync(id);
            _context.Menus.Remove(menu);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MenuExists(int id)
        {
            return _context.Menus.Any(e => e.Id == id);
        }
    }
}

Vendor/Controllers/SalesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Vendor.Data;
using Vendor.Models;
using Vendor.Models.ViewModels;
using static Vendor.Utilities.Enums;
using static Vendor.Helpers.Helpers;

namespace Vendor.Controllers
{
    [Authorize]
    public class SalesController : BaseController
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;


        public SalesController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Sales
        public async Task<IActionResult> Index(int? outletId)
        {
            var applicationDbContext = _context.Sales.Include(s => s.Menu).Include(s => s.Transaction);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Sales/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sale = await _context.Sales
                .Include(s => s.Menu)
                .Include(s => s.Transaction)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (sale == null)
            {
                return NotFound();
            }

            return View(sale);
        }

        // GET: Sales/Create
        public IActionResult Create(int outletId)
        {

            //ViewData["TransactionId"] = new SelectList(_context.Transactions, "Id", "Id");
            var outlet = _context.Outlets.Where(o=>o.Id == outletId).Include(o=>o.Store).FirstOrDefault();
            if(outlet == null)
            {
                throw new Exception();
            }
            var customers = _context.Customers.Where(c => c.OutletId == outletId).ToList();

            var menu = _context.Menus.Where(m=>m.OutletId== outletId).ToList();
            var viewModel = new SalesCreateViewModel()
            {
                Menu = menu,
                outlet = outlet,
                store = outlet.Store,

            };
            if(menu.Count < 1)
            {
                DisplayAlert("You need to create at least an item before you can start selling");
                return RedirectToAction("Index", "Menus", new {outletId = outletId});
            }
            var paymentTypes = new List<string>();
                
             foreach (var item in Enum.GetNames(typeof(PaymentTypes)))
            {
                paymentTypes.Add(item);
            }
            ViewData["PaymentTypes"] = new SelectList(paymentTypes);
            ViewData["Customers"] = new SelectList(customers, "Id", "UserName");
            ViewData["MenuId"] = new SelectList(menu, "Id", "Name");
            ViewData["OutletId"] = outletId;
            return View(viewModel);
        }

        // POST: Sales/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(SalesCreateViewModel sale)
        {

          
            var transaction = new Transaction()
            {
                OutletId = 1,
                CashierId = _context.ApplicationUsers.FirstOrDefault(c=>c.Id == sale.CashierId).Id,
                CustomerId = _context.Customers.FirstOrDefault(c=>c.Id ==sale.CustomerId).Id,
            };
            _context.Transactions.Add(transaction);
           var saveTransaction = await _context.SaveChangesAsync();
            if (saveTransaction.Equals(0))
            {
                return BadRequest();
            }
            if (ModelState.IsValid)
            {
                var menu1 = new Menu
                {
                    Id = 1,
                    Amount = 1000
                };
                var menu2 = new Menu
                {
                    Id = 3,
                    Amount = 500
                };

                sale.Menu.Add(menu1); sale.Menu.Add(menu2);
                foreach (var item in sale.Menu)
                {
                    var s = new Sale()
                    {
                        TransactionId = transaction.Id,
                        MenuId = item.Id
                    };
                    _context.Add(s);
                    await _context.SaveChangesAsync();
                }
               
                return RedirectToAction(nameof(Index));
            }
            ViewData["MenuId"] = new SelectList(_context.Menus, "Id", "Id", sale.MenuId);
            ViewData["TransactionId"] = new SelectList(_context.Transactions, "Id", "Id", sale.TransactionId);
            return View(sale);


        }

        // GET: Sales/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sale = await _context.Sales.FindAsync(id);
            if (sale == null)
            {
                return NotFound();
            }
            ViewData["MenuId"] = new SelectList(_context.Menus, "Id", "Id", sale.MenuId);
            ViewData["TransactionId"] = new SelectList(_context.Transactions, "Id", "Id", sale.TransactionId);
            return View(sale);
        }

        // POST: Sales/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,TransactionId,MenuId,IsDeleted")] Sale sale)
        {
            if (id != sale.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(sale);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SaleExists(sale.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MenuId"] = new SelectList(_context.Menus, "Id", "Id", sale.MenuId);
            ViewData["TransactionId"] = new SelectList(_context.Transactions, "Id", "Id", sale.TransactionId);
            return View(sale);
        }

        // GET: Sales/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sale = await _context.Sales
                .Include(s => s.Menu)
                .Include(s => s.Transaction)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (sale == null)
            {
                return NotFound();
            }

            return View(sale);
        }

        // POST: Sales/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var sale = await _context.Sales.FindAsync(id);
            _context.Sales.Remove(sale);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SaleExists(int id)
        {
            return _context.Sales.Any(e => e.Id == id);
        }
    }
}

Vendor/Views/Outlets/Create.cshtml
@model Vendor.Models.Outlet

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Location</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StoreId" class="control-label"></label>
                <select asp-for="StoreId" class ="form-control" asp-items="ViewBag.StoreId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Vendor/Views/Outlets/Delete.cshtml
@model Vendor.Models.Outlet

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Location</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Store)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Store.Id)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Vendor/Views/Outlets/Details.cshtml
@model Vendor.Models.Outlet

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Location</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Store)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Store.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    @*<a asp-action="Create" asp-controller="Menus" asp-route-storeId="@Model.StoreId">Create Menu</a> |*@
    <a asp-action="Index" asp-controller="Menus" asp-route-outletId="@Model.Id">Menu</a> |
    <a asp-action="Create" asp-controller="Cashiers" asp-route-id="@Model.Id">Create Cashiers</a> |
    <a asp-action="Create" asp-controller="Customers" asp-route-id="@Model.Id">Create Customers</a> |
    <a asp-action="Index" asp-controller="Transactions" asp-route-outletId="@Model.Id">Transactions</a>|
    <a asp-action="Index" asp-controller="Accounts" asp-route-outletId="@Model.Id">Transactions</a>|
    @*<a asp-action="Index" asp-controller="Sales" asp-route-outletId="@Model.Id">Sales</a> |*@
    <a asp-action="Index">Back to List</a>
</div>

Vendor/Views/Outlets/Edit.cshtml
@model Vendor.Models.Outlet

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Location</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StoreId" class="control-label"></label>
                <select asp-for="StoreId" class="form-control" asp-items="ViewBag.StoreId"></select>
                <span asp-validation-for="StoreId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Vendor/Views/Outlets/Index.cshtml
@model Vendor.Models.ViewModels.OutletIndexViewModel

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Outlets</h1>
<br />
<p>
    <a class="btn btn-primary" asp-action="Create" asp-route-storeId="@Model.storeId">Create New Outlet</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Outlets)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StoreName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Outlets) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Store.Name)
            </td>
            <td>
                <a asp-action="Index" asp-controller="Accounts" asp-route-id="@item.Id">Accounts</a> |
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>